from PyQt5 import QtCore, QtWidgets

class Ui_ConstructorWindow(object):
    def setupUi(self, ConstructorWindow):
        ConstructorWindow.setObjectName("ConstructorWindow")
        ConstructorWindow.resize(324, 346)
        self.centralwidget = QtWidgets.QWidget(ConstructorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.levelview = QtWidgets.QTableWidget(self.centralwidget)
        self.levelview.setGeometry(QtCore.QRect(0, 0, 323, 323))
        self.levelview.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.levelview.setRowCount(5)
        self.levelview.setColumnCount(5)
        self.levelview.setObjectName("levelview")
        self.levelview.horizontalHeader().setVisible(False)
        self.levelview.horizontalHeader().setDefaultSectionSize(64)
        self.levelview.horizontalHeader().setMinimumSectionSize(64)
        self.levelview.verticalHeader().setVisible(False)
        self.levelview.verticalHeader().setDefaultSectionSize(64)
        self.levelview.verticalHeader().setMinimumSectionSize(64)
        ConstructorWindow.setCentralWidget(self.centralwidget)
        self.mainmenu = QtWidgets.QMenuBar(ConstructorWindow)
        self.mainmenu.setGeometry(QtCore.QRect(0, 0, 324, 21))
        self.mainmenu.setObjectName("mainmenu")
        self.level = QtWidgets.QMenu(self.mainmenu)
        self.level.setObjectName("level")
        self.delete = QtWidgets.QMenu(self.mainmenu)
        self.delete.setObjectName("delete")
        self.add = QtWidgets.QMenu(self.mainmenu)
        self.add.setObjectName("add")
        ConstructorWindow.setMenuBar(self.mainmenu)
        self.save = QtWidgets.QAction(ConstructorWindow)
        self.save.setObjectName("save")
        self.clear = QtWidgets.QAction(ConstructorWindow)
        self.clear.setObjectName("clear")
        self.delrow = QtWidgets.QAction(ConstructorWindow)
        self.delrow.setObjectName("delrow")
        self.delcol = QtWidgets.QAction(ConstructorWindow)
        self.delcol.setObjectName("delrow")
        self.addrow = QtWidgets.QAction(ConstructorWindow)
        self.addrow.setObjectName("addrow")
        self.addcol = QtWidgets.QAction(ConstructorWindow)
        self.addcol.setObjectName("addcol")
        self.level.addAction(self.save)
        self.level.addAction(self.clear)
        self.delete.addAction(self.delrow)
        self.delete.addAction(self.delcol)
        self.add.addAction(self.addrow)
        self.add.addAction(self.addcol)
        self.mainmenu.addAction(self.level.menuAction())
        self.mainmenu.addAction(self.add.menuAction())
        self.mainmenu.addAction(self.delete.menuAction())

        self.retranslateUi(ConstructorWindow)
        QtCore.QMetaObject.connectSlotsByName(ConstructorWindow)

    def retranslateUi(self, ConstructorWindow):
        _translate = QtCore.QCoreApplication.translate
        ConstructorWindow.setWindowTitle(_translate("ConstructorWindow", "Конструктор"))
        self.level.setTitle(_translate("ConstructorWindow", "Уровень"))
        self.add.setTitle(_translate("ConstructorWindow", "Добавить"))
        self.delete.setTitle(_translate("ConstructorWindow", "Удалить"))
        self.save.setText(_translate("ConstructorWindow", "Сохранить"))
        self.clear.setText(_translate("ConstructorWindow", "Очистить"))
        self.addrow.setText(_translate("ConstructorWindow", "Строку"))
        self.addcol.setText(_translate("ConstructorWindow", "Столбец"))
        self.delrow.setText(_translate("ConstructorWindow", "Строку"))
        self.delcol.setText(_translate("ConstructorWindow", "Столбец"))
